// ANCIENNE METHODE
// export const CREATE_MINION = 'CREATE_MINION';
// export const DESTROY_MINION = 'DESTROY_MINION';

// NOUVELLE METHODE : OBJET

const actions = {
  // INCREMENTATION / DECREMENTATION
  CREATE_MINION: 'CREATE_MINION',
  DESTROY_MINION: 'DESTROY_MINION',
  // CONSTRUCTION / DESTRUCTION EQUIPE
  CREATE_TEAM: 'CREATE_TEAM_MINIONS',
  DESTROY_TEAM: 'DESTROY_TEAM_MINIONS',
  // SAUVEGARDE
  SAVE: 'SAVE',
  // INCREMENTATION AUTO DE MINIONS
  AUTO_ENROLL: 'AUTO_ENROLL',
};

export default actions;
